name: tunnel-server

services:
  tunnel:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: tunnel-server
    ports: ["8080:8080"]

  app:
    image: crccheck/hello-world
    container_name: tunneled-app
    ports: ["8888:8000"]
