on:
   workflow_call:
      outputs:
         tag:
            description: the latest tag
            value: ${{ jobs.fetch.outputs.tag }}

jobs:
   fetch:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Get Latest Tag
           uses: actions-ecosystem/action-get-latest-tag@v1
           id: get
           with:
              semver_only: true

         - name: Fail if missing
           if: ${{ steps.get.outputs.tag == '' }}
           run: exit 1

         - name: Build Version
           id: build
           run: echo "tag=${{ steps.get.outputs.tag }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

      outputs:
         tag: ${{ steps.build.outputs.tag }}
